<?php

/**
 * @file
 * Adds uc_cart_item tokens for attribute values of products.
 *
 * Originally written by Chris Yu <http://drupal.org/user/202205>.
 * Now updated to Drupal 6 / Ubercart 2, enhanced, and maintained by
 * Tim Rohaly <http://drupal.org/user/202830>.
 *
 * @author Tim Rohaly.    <http://drupal.org/user/202830>
 */


/**
 * Implements hook_token_info().
 */
function uc_attribute_tokens_token_info() {
//'attribute' || $type == 'ubercart' || $type == 'all') {
  $types = array(
    'name' => t('(attribute name)'),
    'description' => t('Tokens corresponding to Ubercart Product attributes.'),
    'needs-data' => 'node',
  );

  $tokens['(attribute name)'] = array(
    'name' => t('(attribute name)'),
    'description' => t('Product attributes are made into tokens that match their name field.'),
  );

  return array(
    'types' => array('ubercart' => $types),
    'tokens' => array('ubercart' => $tokens),
  );
}


/**
 * Implements hook_tokens().
 */
function uc_attribute_tokens_tokens($type, $tokens, $data = array(), $options = array()) {
  if ($type == 'attribute' && uc_product_is_product($data['node'])) {
    $attributes = uc_product_get_attributes($data['node']->nid);
    // Loop over all product attributes
    foreach ($attributes as $attribute) {
      // Set attributes token to the value selected for this product
      $option_array = $data['node']->data['attributes'][$attribute->label];

      // If option doesn't appear in product data, then it was not
      // required and not chosen.  Skip.
      if (isset($option_array)) {
        // Checkbox attributes may have more than one selection
        $values[$attribute->label] = implode(', ', $option_array);
      }
    }

    return $values;
  }
}
