<?php

/**
 * @file
 * Install, Uninstall and schema hooks for the module.
 */

/**
 * Implements hook_uninstall().
 */
function reading_progress_bar_uninstall() {
  // Delete all variables which are named like reading_progress_bar_%.
  db_delete('variable')
    ->condition('name', 'reading_progress_bar_%', 'LIKE')
    ->execute();
  // Clear variables cache.
  cache_clear_all('variables', 'cache_bootstrap');
}
